# Generated by Django 2.0.5 on 2018-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('mem', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('time_login', models.DateTimeField()),
            ],
        ),
    ]
