# Generated by Django 2.0.5 on 2018-05-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerialCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialcode', models.CharField(max_length=256, unique=True)),
                ('mac', models.CharField(max_length=64, null=True)),
                ('auth_key', models.CharField(max_length=256)),
                ('time_activated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
