# Generated by Django 2.0.5 on 2018-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialcode',
            name='auth_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='serialcode',
            name='time_activated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
