# Generated by Django 2.0.5 on 2018-05-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialcode', '0002_auto_20180519_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialcode',
            name='auth_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='serialcode',
            name='mac',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
