# Generated by Django 2.0.5 on 2018-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.CharField(max_length=64)),
                ('calulation_ability', models.IntegerField(default=0)),
                ('earning_possibility', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gtype', models.CharField(max_length=64)),
                ('calculation', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=255)),
                ('day_earning', models.CharField(max_length=255)),
                ('week_earning', models.CharField(max_length=255)),
                ('month_earning', models.CharField(max_length=255)),
            ],
        ),
    ]
