# Generated by Django 2.0.5 on 2018-05-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.CharField(max_length=256)),
                ('miner', models.IntegerField()),
                ('hashrate', models.FloatField()),
                ('blocks', models.FloatField()),
                ('last_blocks', models.DateTimeField()),
                ('last_beat', models.DateTimeField()),
                ('difficulty', models.FloatField()),
                ('variance', models.FloatField()),
                ('status', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='coin_cn_name',
            field=models.CharField(default='ETH', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='coin_en_name',
            field=models.CharField(default='ETH', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='coin_link',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='coin_nickname',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miningpool',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Coin'),
        ),
    ]
