# Generated by Django 2.0.5 on 2018-05-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180524_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningpool',
            name='url',
            field=models.CharField(default='https://clo.2miners.com/zh', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miningpool',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_miningpool', to='website.Coin'),
        ),
    ]
