# Generated by Django 2.0.5 on 2018-05-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_coin_coin_3rd_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='coin_3rd_code',
            new_name='coin_3rd_id',
        ),
    ]
