# Generated by Django 2.0.5 on 2018-06-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180528_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=126)),
                ('app', models.CharField(max_length=126, unique=True)),
                ('url', models.CharField(max_length=2048)),
                ('time_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
